version: '3'

services:
    mongoRepl:
      image: mongors
      build:
          context: .
          args:
              - MONGO_VERSION=${MONGO_VERSION}
      container_name: ${CONTAINER_NAME}
      ports:
          - ${CONTAINER_PORT}:27017
      volumes:
          - /data/db:/data/db
      restart: always
      command: mongod --replSet "${REPLICA_SET_NAME}" --keyFile /home/mongo.key
