version: '3'

services:
    mongoRepl:
      image: mongos
      build:
          context: .
          args:
              - MONGO_VERSION=${MONGO_VERSION}
      container_name: ${CONTAINER_NAME}
      ports:
          - ${CONTAINER_PORT}:27017
      volumes:
          - /data/db:/data/db
      restart: always
      command: mongos --configdb "${REPLICA_SET_NAME}/${CONF_IP}" --keyFile /home/mongo.key --bind_ip_all
